# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('uid', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=1024)),
                ('published', models.DateTimeField(null=True)),
                ('extracted', models.DateTimeField(null=True)),
                ('title', models.CharField(max_length=1024)),
                ('text', models.CharField(max_length=8096)),
            ],
        ),
    ]
