# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='url',
            new_name='link',
        ),
    ]
