# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20161008_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
