# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20161008_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('slug', models.SlugField(max_length=128, primary_key=True, serialize=False)),
                ('link', models.URLField()),
            ],
        ),
    ]
